// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package cluster

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	ec2apitypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"
	snsapitypes "github.com/aws-controllers-k8s/sns-controller/apis/v1alpha1"

	svcapitypes "github.com/aws-controllers-k8s/memorydb-controller/apis/v1alpha1"
)

// +kubebuilder:rbac:groups=sns.services.k8s.aws,resources=topics,verbs=get;list
// +kubebuilder:rbac:groups=sns.services.k8s.aws,resources=topics/status,verbs=get;list

// +kubebuilder:rbac:groups=ec2.services.k8s.aws,resources=securitygroups,verbs=get;list
// +kubebuilder:rbac:groups=ec2.services.k8s.aws,resources=securitygroups/status,verbs=get;list

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve
// those reference field(s) into target field(s).
// It returns an AWSResource with resolved reference(s), and an error if the
// passed AWSResource's reference field(s) cannot be resolved.
// This method also adds/updates the ConditionTypeReferencesResolved for the
// AWSResource.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, error) {
	namespace := res.MetaObject().GetNamespace()
	ko := rm.concreteResource(res).ko.DeepCopy()
	err := validateReferenceFields(ko)
	if err == nil {
		err = resolveReferenceForACLName(ctx, apiReader, namespace, ko)
	}
	if err == nil {
		err = resolveReferenceForParameterGroupName(ctx, apiReader, namespace, ko)
	}
	if err == nil {
		err = resolveReferenceForSNSTopicARN(ctx, apiReader, namespace, ko)
	}
	if err == nil {
		err = resolveReferenceForSecurityGroupIDs(ctx, apiReader, namespace, ko)
	}
	if err == nil {
		err = resolveReferenceForSnapshotName(ctx, apiReader, namespace, ko)
	}
	if err == nil {
		err = resolveReferenceForSubnetGroupName(ctx, apiReader, namespace, ko)
	}

	// If there was an error while resolving any reference, reset all the
	// resolved values so that they do not get persisted inside etcd
	if err != nil {
		ko = rm.concreteResource(res).ko.DeepCopy()
	}
	if hasNonNilReferences(ko) {
		return ackcondition.WithReferencesResolvedCondition(&resource{ko}, err)
	}
	return &resource{ko}, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.Cluster) error {
	if ko.Spec.ACLRef != nil && ko.Spec.ACLName != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("ACLName", "ACLRef")
	}
	if ko.Spec.ACLRef == nil && ko.Spec.ACLName == nil {
		return ackerr.ResourceReferenceOrIDRequiredFor("ACLName", "ACLRef")
	}
	if ko.Spec.ParameterGroupRef != nil && ko.Spec.ParameterGroupName != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("ParameterGroupName", "ParameterGroupRef")
	}
	if ko.Spec.SNSTopicRef != nil && ko.Spec.SNSTopicARN != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("SNSTopicARN", "SNSTopicRef")
	}
	if ko.Spec.SecurityGroupRefs != nil && ko.Spec.SecurityGroupIDs != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("SecurityGroupIDs", "SecurityGroupRefs")
	}
	if ko.Spec.SnapshotRef != nil && ko.Spec.SnapshotName != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("SnapshotName", "SnapshotRef")
	}
	if ko.Spec.SubnetGroupRef != nil && ko.Spec.SubnetGroupName != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("SubnetGroupName", "SubnetGroupRef")
	}
	return nil
}

// hasNonNilReferences returns true if resource contains a reference to another
// resource
func hasNonNilReferences(ko *svcapitypes.Cluster) bool {
	return false || (ko.Spec.ACLRef != nil) || (ko.Spec.ParameterGroupRef != nil) || (ko.Spec.SNSTopicRef != nil) || (ko.Spec.SecurityGroupRefs != nil) || (ko.Spec.SnapshotRef != nil) || (ko.Spec.SubnetGroupRef != nil)
}

// resolveReferenceForACLName reads the resource referenced
// from ACLRef field and sets the ACLName
// from referenced resource
func resolveReferenceForACLName(
	ctx context.Context,
	apiReader client.Reader,
	namespace string,
	ko *svcapitypes.Cluster,
) error {
	if ko.Spec.ACLRef != nil && ko.Spec.ACLRef.From != nil {
		arr := ko.Spec.ACLRef.From
		if arr == nil || arr.Name == nil || *arr.Name == "" {
			return fmt.Errorf("provided resource reference is nil or empty: ACLRef")
		}
		obj := &svcapitypes.ACL{}
		if err := getReferencedResourceState_ACL(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return err
		}
		ko.Spec.ACLName = (*string)(obj.Spec.Name)
	}

	return nil
}

// getReferencedResourceState_ACL looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_ACL(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.ACL,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceSynced, refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"ACL",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"ACL",
			namespace, name)
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"ACL",
			namespace, name)
	}
	if obj.Spec.Name == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"ACL",
			namespace, name,
			"Spec.Name")
	}
	return nil
}

// resolveReferenceForParameterGroupName reads the resource referenced
// from ParameterGroupRef field and sets the ParameterGroupName
// from referenced resource
func resolveReferenceForParameterGroupName(
	ctx context.Context,
	apiReader client.Reader,
	namespace string,
	ko *svcapitypes.Cluster,
) error {
	if ko.Spec.ParameterGroupRef != nil && ko.Spec.ParameterGroupRef.From != nil {
		arr := ko.Spec.ParameterGroupRef.From
		if arr == nil || arr.Name == nil || *arr.Name == "" {
			return fmt.Errorf("provided resource reference is nil or empty: ParameterGroupRef")
		}
		obj := &svcapitypes.ParameterGroup{}
		if err := getReferencedResourceState_ParameterGroup(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return err
		}
		ko.Spec.ParameterGroupName = (*string)(obj.Spec.Name)
	}

	return nil
}

// getReferencedResourceState_ParameterGroup looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_ParameterGroup(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.ParameterGroup,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceSynced, refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"ParameterGroup",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"ParameterGroup",
			namespace, name)
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"ParameterGroup",
			namespace, name)
	}
	if obj.Spec.Name == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"ParameterGroup",
			namespace, name,
			"Spec.Name")
	}
	return nil
}

// resolveReferenceForSNSTopicARN reads the resource referenced
// from SNSTopicRef field and sets the SNSTopicARN
// from referenced resource
func resolveReferenceForSNSTopicARN(
	ctx context.Context,
	apiReader client.Reader,
	namespace string,
	ko *svcapitypes.Cluster,
) error {
	if ko.Spec.SNSTopicRef != nil && ko.Spec.SNSTopicRef.From != nil {
		arr := ko.Spec.SNSTopicRef.From
		if arr == nil || arr.Name == nil || *arr.Name == "" {
			return fmt.Errorf("provided resource reference is nil or empty: SNSTopicRef")
		}
		obj := &snsapitypes.Topic{}
		if err := getReferencedResourceState_Topic(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return err
		}
		ko.Spec.SNSTopicARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
	}

	return nil
}

// getReferencedResourceState_Topic looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Topic(
	ctx context.Context,
	apiReader client.Reader,
	obj *snsapitypes.Topic,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceSynced, refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Topic",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Topic",
			namespace, name)
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Topic",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Topic",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}

// resolveReferenceForSecurityGroupIDs reads the resource referenced
// from SecurityGroupRefs field and sets the SecurityGroupIDs
// from referenced resource
func resolveReferenceForSecurityGroupIDs(
	ctx context.Context,
	apiReader client.Reader,
	namespace string,
	ko *svcapitypes.Cluster,
) error {
	if len(ko.Spec.SecurityGroupRefs) > 0 {
		resolved0 := []*string{}
		for _, iter0 := range ko.Spec.SecurityGroupRefs {
			arr := iter0.From
			if arr == nil || arr.Name == nil || *arr.Name == "" {
				return fmt.Errorf("provided resource reference is nil or empty: SecurityGroupRefs")
			}
			obj := &ec2apitypes.SecurityGroup{}
			if err := getReferencedResourceState_SecurityGroup(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
				return err
			}
			resolved0 = append(resolved0, (*string)(obj.Status.ID))
		}
		ko.Spec.SecurityGroupIDs = resolved0
	}

	return nil
}

// getReferencedResourceState_SecurityGroup looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_SecurityGroup(
	ctx context.Context,
	apiReader client.Reader,
	obj *ec2apitypes.SecurityGroup,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceSynced, refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"SecurityGroup",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"SecurityGroup",
			namespace, name)
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"SecurityGroup",
			namespace, name)
	}
	if obj.Status.ID == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"SecurityGroup",
			namespace, name,
			"Status.ID")
	}
	return nil
}

// resolveReferenceForSnapshotName reads the resource referenced
// from SnapshotRef field and sets the SnapshotName
// from referenced resource
func resolveReferenceForSnapshotName(
	ctx context.Context,
	apiReader client.Reader,
	namespace string,
	ko *svcapitypes.Cluster,
) error {
	if ko.Spec.SnapshotRef != nil && ko.Spec.SnapshotRef.From != nil {
		arr := ko.Spec.SnapshotRef.From
		if arr == nil || arr.Name == nil || *arr.Name == "" {
			return fmt.Errorf("provided resource reference is nil or empty: SnapshotRef")
		}
		obj := &svcapitypes.Snapshot{}
		if err := getReferencedResourceState_Snapshot(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return err
		}
		ko.Spec.SnapshotName = (*string)(obj.Spec.Name)
	}

	return nil
}

// getReferencedResourceState_Snapshot looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Snapshot(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.Snapshot,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceSynced, refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Snapshot",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Snapshot",
			namespace, name)
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Snapshot",
			namespace, name)
	}
	if obj.Spec.Name == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Snapshot",
			namespace, name,
			"Spec.Name")
	}
	return nil
}

// resolveReferenceForSubnetGroupName reads the resource referenced
// from SubnetGroupRef field and sets the SubnetGroupName
// from referenced resource
func resolveReferenceForSubnetGroupName(
	ctx context.Context,
	apiReader client.Reader,
	namespace string,
	ko *svcapitypes.Cluster,
) error {
	if ko.Spec.SubnetGroupRef != nil && ko.Spec.SubnetGroupRef.From != nil {
		arr := ko.Spec.SubnetGroupRef.From
		if arr == nil || arr.Name == nil || *arr.Name == "" {
			return fmt.Errorf("provided resource reference is nil or empty: SubnetGroupRef")
		}
		obj := &svcapitypes.SubnetGroup{}
		if err := getReferencedResourceState_SubnetGroup(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return err
		}
		ko.Spec.SubnetGroupName = (*string)(obj.Spec.Name)
	}

	return nil
}

// getReferencedResourceState_SubnetGroup looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_SubnetGroup(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.SubnetGroup,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceSynced, refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"SubnetGroup",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"SubnetGroup",
			namespace, name)
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"SubnetGroup",
			namespace, name)
	}
	if obj.Spec.Name == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"SubnetGroup",
			namespace, name,
			"Spec.Name")
	}
	return nil
}
