---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-memorydb-reader
  namespace: default
rules:
- apiGroups:
  - memorydb.services.k8s.aws
  resources:
  - acls
  - clusters
  - parametergroups
  - subnetgroups
  - users
  verbs:
  - get
  - list
  - watch
