// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AZStatus string

const (
	AZStatus_multiaz  AZStatus = "multiaz"
	AZStatus_singleaz AZStatus = "singleaz"
)

type AuthenticationType string

const (
	AuthenticationType_iam         AuthenticationType = "iam"
	AuthenticationType_no_password AuthenticationType = "no-password"
	AuthenticationType_password    AuthenticationType = "password"
)

type DataTieringStatus string

const (
	DataTieringStatus_false DataTieringStatus = "false"
	DataTieringStatus_true  DataTieringStatus = "true"
)

type InputAuthenticationType string

const (
	InputAuthenticationType_iam      InputAuthenticationType = "iam"
	InputAuthenticationType_password InputAuthenticationType = "password"
)

type ServiceUpdateStatus string

const (
	ServiceUpdateStatus_available   ServiceUpdateStatus = "available"
	ServiceUpdateStatus_complete    ServiceUpdateStatus = "complete"
	ServiceUpdateStatus_in_progress ServiceUpdateStatus = "in-progress"
	ServiceUpdateStatus_scheduled   ServiceUpdateStatus = "scheduled"
)

type ServiceUpdateType string

const (
	ServiceUpdateType_security_update ServiceUpdateType = "security-update"
)

type SourceType string

const (
	SourceType_acl             SourceType = "acl"
	SourceType_cluster         SourceType = "cluster"
	SourceType_node            SourceType = "node"
	SourceType_parameter_group SourceType = "parameter-group"
	SourceType_subnet_group    SourceType = "subnet-group"
	SourceType_user            SourceType = "user"
)

type UpdateStrategy string

const (
	UpdateStrategy_coordinated   UpdateStrategy = "coordinated"
	UpdateStrategy_uncoordinated UpdateStrategy = "uncoordinated"
)
